### ISSUE TITLE
Permissions error in osc in conjunction with nsjail

### ISSUE THREAD

**Issue by mgerstner** [openSUSE/obs-service-cargo_audit#4]
The new `nsjail` containment is giving me trouble on my current Tumbleweed installation:

```
🍿 unpacking and scanning zypp-gui ...
🚨 -- cargo_audit failed
nsjail --really_quiet --config scan.cfg --cwd /home/jenkins/workspaces/workspace/rust_cargo_audit/obs-service-cargo_audit/openSUSE:Factory/zypp-gui --bindmount /home/jenkins
/workspaces/workspace/rust_cargo_audit/obs-service-cargo_audit:/home/jenkins/workspaces/workspace/rust_cargo_audit/obs-service-cargo_audit /usr/bin/osc service lr cargo_audit
Traceback (most recent call last):
  File "/usr/bin/osc", line 45, in <module>
    r = babysitter.run(osccli)
  File "/usr/lib/python3.8/site-packages/osc/babysitter.py", line 69, in run
    return prg.main(argv)
  File "/usr/lib/python3.8/site-packages/osc/cmdln.py", line 339, in main
    self.postoptparse()
  File "/usr/lib/python3.8/site-packages/osc/commandline.py", line 137, in postoptparse
    conf.get_config(override_conffile = self.options.conffile,
  File "/usr/lib/python3.8/site-packages/osc/conf.py", line 884, in get_config
    os.chmod(conffile, 0o600)
OSError: [Errno 30] Read-only file system: '/home/jenkins/.config/osc/oscrc'
```

It turns out `osc` is not using the smartest code there:

```
    conffile = os.path.expanduser(conffile)
    if not os.path.exists(conffile):
        raise oscerr.NoConfigfile(conffile, \
                                  account_not_configured_text % conffile)

    # okay, we made sure that oscrc exists

    # make sure it is not world readable, it may contain a password.
    os.chmod(conffile, 0o600)
```

The unconditional `chmod` is problematic. The user should optimally be asked and be informed about any insecure mode. We can try to approach the `osc` project about that or work around the problem by creating a writable copy of the file or something like that.

**Comment by Firstyear** [comment]
I've submitted a few PR's to OSC so I can probably fix this tbh.
