### ISSUE TITLE
zstd seems to be forgotten

### ISSUE THREAD

**Issue by uncomfyhalomacro** [openSUSE/obs-service-cargo_audit#7]
Probably an easy fix since it's just zstd was forgotten to be added.

Sample error log
```

WARNING: To avoid cargo install rebuilding the binary in the install stage
         all environment variables must be the same as in the build stage.

INFO:obs-service-cargo_vendor:Starting compression ...
INFO:obs-service-cargo_vendor:Success
INFO:obs-service-cargo_audit: Running OBS Source Service 🛒: obs-service-cargo_audit
Traceback (most recent call last):
  File "/usr/lib/obs/service/cargo_audit", line 239, in <module>
    main()
  File "/usr/lib/obs/service/cargo_audit", line 229, in main
    status = do_cargo_audit(workdir, lsrcdir, lockfile)
  File "/usr/lib/obs/service/cargo_audit", line 143, in do_cargo_audit
    srcdirs = do_extract(workdir, tmpdirname)
  File "/usr/lib/obs/service/cargo_audit", line 129, in do_extract
    with tarfile.open(f"{from_dir}/{src}", "r:*") as tar:
  File "/usr/lib64/python3.10/tarfile.py", line 1804, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('invalid header')
Aborting: service call failed:  /usr/lib/obs/service/cargo_audit --outdir /home/uncomfy/development/obs/Base:System/just/tmpz_tt3adb.cargo_audit.service
```

I had to do the cargo audit myself for now.

**Comment by Firstyear** [comment]
it's not as easy as you might thing - it certainly was forgotten but the fix is similar to https://github.com/openSUSE/obs-service-cargo_vendor/blob/master/cargo_vendor#L132 because the python tar module does not support zst natively. So if you want you can have a go at the fix or I can do it :)

**Comment by uncomfyhalomacro** [comment]
Oh! apologies. i thought the python tar module supports zstd 😅

**Comment by Firstyear** [comment]
No need to apologise :)
